// apps/app_shell/main.cpp
// Phase 1 entrypoint: boots a Qt Quick window to prove the full toolchain
// (compiler, linker, Qt6 discovery, QML loading) works end-to-end.
//
// Later phases expand this into the real application bootstrap:
//   Phase 2 — structured logging + config + thread pool init
//   Phase 3 — Suno network client wiring
//   Phase 4 — projectM render node registration
//   Phase 5 — QML shell + overlay compositor
//   Phase 6 — diagnostics HUD + error fallbacks

#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QQmlError>
#include <QString>
#include <QTextStream>
#include <QtGlobal>

namespace {
// Minimal stdout tracer used until the Phase 2 structured logger exists.
void trace(const QString& msg) { QTextStream(stdout) << "[boot] " << msg << Qt::endl; }
} // namespace

int main(int argc, char* argv[])
{
    // High-DPI rounding policy that matters for the projectM canvas (Phase 4).
    // Must be set before QGuiApplication construction.
    QGuiApplication::setHighDpiScaleFactorRoundingPolicy(
        Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);

    QGuiApplication app(argc, argv);
    QGuiApplication::setApplicationName("Suno Creator");
    QGuiApplication::setApplicationVersion(SUNO_VERSION);
    QGuiApplication::setOrganizationName("SunoCreator");

    QQmlApplicationEngine engine;

    // Surface the version to QML for the Phase 6 HUD.
    engine.rootContext()->setContextProperty(
        "appBuildVersion", QString::fromLatin1(SUNO_VERSION));

    // Forward every QML warning to stdout — Qt can swallow these silently,
    // which makes debugging in-tree modules painful.
    QObject::connect(&engine, &QQmlEngine::warnings,
                     [](const QList<QQmlError>& warnings) {
                         for (const QQmlError& w : warnings)
                             trace("QML: " + w.toString());
                     });

    // Exit the whole app if QML creation fails (queued so the engine finishes
    // its current work first).
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreationFailed, &app,
                     []() { QCoreApplication::exit(-1); }, Qt::QueuedConnection);

    trace(QString("starting Suno Creator v%1").arg(SUNO_VERSION));
    engine.loadFromModule("SunoCreator", "Main");

    if (engine.rootObjects().isEmpty()) {
        // Defensive fallback: try the compiled-in resource URL directly.
        // Matches the qrc prefix generated by qt_add_qml_module (QTP0001 NEW).
        trace("loadFromModule produced no root object; trying resource URL.");
        engine.load(QUrl(QStringLiteral("qrc:/qt/qml/SunoCreator/Main.qml")));
        if (engine.rootObjects().isEmpty()) {
            trace("QML load failed completely; aborting.");
            return -1;
        }
    }

    trace("QML loaded; entering event loop.");
    return app.exec();
}
